`timescale 1ns / 1ps
//-------------------------------------------------------------------------------
// Company:  QHYCCD
// Engineer: YangSK
// 
// Create Date: 2022/5/16
// Design Name: T35_TOP
// Module Name: ddr3_state
// Project Name: T35_FRAMEWORK
// Target Devices: t35f324
// Tool Versions: EFINITY21.2
// Description:   ddr3 :MT41K256M16TW-107:P£»  1.07ns @ CL = 13 (DDR3-1866) -107  ; row 15bit ;  colum 10bit  bank 3bit ,512Mbyte,addre is 29bit
// Dependencies:  DDR3 ADDRESS[27:0] =2^28*16/1024/1024/1024=4Gbit; AXI ADDRESS is [28:0];every address is 8bit data; 0-1fff_ffff
// 
// Revision:rev1 
// 
// Additional Comments:
// 
//--------------------------------------------------------------------------------

module ddr3_state
		(

		input	wire						clk					,
		input	wire						reset_done			,
		input	wire						DDR_CLG_R			,
		input	wire						ddrpll_locked		,
		input	wire						skip_check			,
		                        			
		input	wire						wr_clk				,
		input	wire	[63:0]				wrddr3_data			,
		input	wire						wrddr3_en			,
		input	wire						rd_clk				,
		input	wire						rddr3_en			,//
		input	wire						fx3_full			,	
		input   wire    [`DDR3ADDRE_MAXBIT:0]	threshold_num		,//unit: byte			
		output	wire	[63:0]				rddr3_data			,
		output	reg							rddr3_vld=0			,
		
		//ddr3 state signals		
		output	reg		[`DDR3ADDRE_MAXBIT:0]	rema_num			,//unit:byte £¬set it to 256bit
		//output	reg							ddr_pfull		=0	,//ddr programme full;if it goes high;ddr can receive only one frame data.
		output  wire     [7:0]				ddr_code		    , // ddrcoe [3:0]==0  {1'b0,1'b0,ddr_pfull,ddr_alempty,ddr_alfull,addr_err,check_fail,init_done_flag};//init_done_flag //check_done_t2
		//ddr axi signals			
		input 								DDR_CTRL_AREADY_0	,  //**Address ready.
  		input [7:0] 						DDR_CTRL_BID_0		,  //not use 
  		input 								DDR_CTRL_BVALID_0	,  //Write response valid. This signal indicates that the channel is signaling a valid write response.                  
  		input [127:0] 						DDR_CTRL_RDATA_0	,  //**Read data.              
  		input [7:0] 						DDR_CTRL_RID_0		,  //Read ID tag. This signal is the identification tag for the read data group of signals generated by the slave. not user                                                                                                                    
  		input 								DDR_CTRL_RLAST_0	,  //**Read last. This signal indicates the last transfer in a read burst.                      
  		input [1:0] 						DDR_CTRL_RRESP_0	,  //Read response. This signal indicates the status of the read transfer
  		input 								DDR_CTRL_RVALID_0	,  //**Read valid
  		input 								DDR_CTRL_WREADY_0	,  //**Write ready. This signal indicates that the slave can accept the write data.
  		                		                                                                                          
  		output reg[31:0] 					DDR_CTRL_AADDR_0	,  //** Address. ATYPE defines whether it is a read or write address. It gives the address of the first transfer in a burst transaction. 
  		output [1:0] 						DDR_CTRL_ABURST_0	,  // Burst type. The burst type and the size determine how the address  for each transfer within the burst is calculated.               
  		output [7:0] 						DDR_CTRL_AID_0		,  // Address ID. This signal identifies the group of address signals. Depends on ATYPE, the ID can be for a read or write address group             
  		output [7:0] 						DDR_CTRL_ALEN_0		,  // Burst length. This signal indicates the number of transfers in a burst
  		output [1:0] 						DDR_CTRL_ALOCK_0	,  // Lock type. This signal provides additional information about the  atomic characteristics of the transfer  
  		output [2:0] 						DDR_CTRL_ASIZE_0	,  // Burst size. This signal indicates the size of each transfer in the burst.                       
  		output reg							DDR_CTRL_ATYPE_0	,  //** This signal distinguishes whether is it is a read or write operation. 0= read and 1 = write.
  		output 								DDR_CTRL_AVALID_0	,  //** Address valid. This signal indicates that the channel is signaling valid address and control information.                                                
  		output 								DDR_CTRL_BREADY_0	,  // Response ready. This signal indicates that the master can accept a write response                            
  		output 								DDR_CTRL_RREADY_0	,  //** Read ready. This signal indicates that the master can accept the read data and response information.                                              
  		output reg	[127:0] 				DDR_CTRL_WDATA_0    ,  //** Write data.
  		output [7:0] 						DDR_CTRL_WID_0		,  // Write ID tag. This signal is the ID tag of the write data transfer
  		output 	reg							DDR_CTRL_WLAST_0	,  //** Write last. This signal indicates the last transfer in a write burst
  		output [15:0] 						DDR_CTRL_WSTRB_0	,  // Write strobes. This signal indicates which byte lanes hold valid data. There is one write strobe bit for each eight bits of the write data bus  
  		output 	reg							DDR_CTRL_WVALID_0      //** Writ

);

localparam ASIZE_0 =3'B100;//a burst is 16 bytes
localparam ADDR_OFFSET = ((`ALEN_0)<<ASIZE_0) ;//ADDR_OFFSET = (ALEN + 1)*32;       
localparam STOP_ADDR = `STOP_ADDR_0 ;//`STOP_ADDR_0 - ADDR_OFFSET-4;	
localparam RDFIFO_COUNT_END = (`ALEN_0*4);//(`RDFIFI_MAX)-(`ALEN_0*2);//
//localparam COUNT_END = log2(RDFIFI_MAX);                
                 
                 
localparam 
		IDLE 			=3'B000,
		INIT_WRITE		=3'B001,
		INIT_CHECK		=3'B010,
		INIT_DONE		=3'B011,
		PRE_WRRTE		=3'B100,//4
		STATE_WRRTE		=3'B101,//5
		PRE_READ		=3'B110,//6
		STATE_READ		=3'B111;//7
	
	

		reg	[2:0]			C_STATE	=0		;
		reg [2:0] 			N_STATE	=0		;
		                	            	
	          	
		wire				wrfifo_full		;
		wire				rdfifo_full		;
	
		//

		wire					rdfifo_empty		;
        reg						ddr_pfull	=0		;
		reg	 [55:0]				wr_addr			=`START_ADDR_0;
		reg  [55:0]				rd_addr			=0	;  
		reg  [55:0]				rema_num_temp	=0	;     		
		wire 					wrfifo_rden			;
		reg 					wrfifo_rdreq	=0	;
		wire [127:0]			wrfifo_rdata  		;   
		wire [`COUNT_ENDBIT:0]				wrfifo_count  		;//how many 128bit
		                    	                	
		wire [`COUNT_ENDBIT:0]				rdfifo_count  		;//how many 128bit
		reg 					rdfifo_rden 	=0	;
                            	
		reg						init_wrdone		=0  ;	
		reg						check_err		=0	;//rise one clock
		reg						wr_cycle		=0	;
		reg						wr_cycle_t0		=0	;
		reg						rd_cycle		=0	;

		reg 					addr_err		=0	;// When the read address is greater than the write address;it will goes high          
		reg						check_done		=0  ;//  
		reg 					check_done_t0	=0	;
		reg 					check_done_t1	=0	;
		reg						check_done_t2	=0	;                                                                                  
						
		reg 					check_fail		=0  ;//if check have error,check_fail is always 1                                          
		reg						ddr_alfull		=0  ;//ddr almost full,ddr won't write any more data. If it goes  high,  will lose data.   
		reg						ddr_alempty		=0  ;//ddr almost empty ,                                                                  
				    		
		reg						ddr_state_rst	=0	;
		reg						ddr_state_rst_t1=0	;
		reg						reset_done_t0	=0	;
		reg						reset_done_t1	=0	;
		                		                  	
		reg 					DDR_CLG_R_T0	=0	;
		reg						DDR_CLG_R_T1	=0	;
		
		reg 					DDR_CTRL_WLAST_1 = 0; 
		wire 					DDR_CTRL_WLAST_2 	;
		reg  [7:0]				wr_cnt			=0	;

		reg 					ddrctrl_avalid_rd =0;//DDR_CTRL_AVALID_RD
		reg 						init_done_flag	=0;
		reg [`DDR3ADDRE_MAXBIT:0]	check_addr		=0;  
		reg [2:0]				skip_check_t		=0; 
		reg  					slip_check_d		=0;
		reg 					WrCheckBit			=0;
		reg 					RdCheckBit			=0;
		reg 					check_err1 			=0;
		reg 					check_err2	 		=0;

assign DDR_CTRL_AID_0=8'h00;
assign DDR_CTRL_ALOCK_0=2'b00;
assign DDR_CTRL_WID_0=8'h00;
assign DDR_CTRL_WSTRB_0=32'hFFFFFFFF;
assign DDR_CTRL_ABURST_0=2'b01;
assign DDR_CTRL_ASIZE_0=ASIZE_0;//a burst is 16 bytes
assign DDR_CTRL_ALEN_0=`ALEN_0-1;// burst times 
assign DDR_CTRL_BREADY_0=1'b1;
assign DDR_CTRL_RREADY_0=1'b1;
 
assign ddr_code = {1'b0,1'b0,ddr_pfull,ddr_alempty,ddr_alfull,addr_err,check_fail,init_done_flag};//init_done_flag //check_done_t2
assign DDR_CTRL_AVALID_0 = (wr_cycle==1&wr_cycle_t0==0)|(ddrctrl_avalid_rd==1);//(rd_cycle==1&rd_cycle_t0==0);
//DDR_CTRL_AVALID_0

initial begin
	check_done  <= 0;
	init_wrdone <= 0;
end 
always @(posedge clk )begin 
	
	ddr_state_rst<= (~reset_done)|(DDR_CLG_R==1)|(~ddrpll_locked);
	ddr_state_rst_t1<=ddr_state_rst;
	//
	
	reset_done_t0<=reset_done;
	reset_done_t1<=reset_done_t0;
	
	DDR_CLG_R_T0<=DDR_CLG_R;
		
	wr_cycle_t0 <= wr_cycle;
	//rd_cycle_t0 <= rd_cycle;
	
	check_done_t0<=check_done;
	check_done_t1<=check_done_t0;
	check_done_t2<=check_done_t1; 
	
	
	skip_check_t<={skip_check_t[1:0],skip_check};
	   
	
end 

always @ (posedge clk )begin 
	if(skip_check==1||skip_check_t>0)begin
		slip_check_d<=1;
	end else if (reset_done_t1==1)begin
		slip_check_d<=0;
	end else begin
		slip_check_d<=slip_check_d;
	end 
end 
//assign slip_check_d=(|skip_check_t) |  skip_check ;

always @ (posedge clk)begin
	if(ddr_state_rst_t1)begin 
		addr_err<=0;
	end else if(wr_addr<rd_addr)begin
		addr_err<=1;
	end else begin
		addr_err<=addr_err;
	end 
end 	
//addr_err

always @(posedge clk )begin 
	if(reset_done_t1==0)begin		
		init_wrdone<=0;
	end else if(C_STATE == INIT_DONE)begin
		init_wrdone<=1;
	end else if(C_STATE==INIT_WRITE&&wr_addr[`DDR3ADDRE_MAXBIT:0]>(STOP_ADDR-1))begin//DDR_CTRL_BVALID_0  DDR_CTRL_WLAST_0==1
		init_wrdone<=1;
	end else begin 
		init_wrdone<=init_wrdone;
	end 
end 
//init_wrdone


//

always @ (posedge clk )begin 
	if(reset_done_t1==0)begin 
		check_addr<=0;
	end else if (C_STATE==INIT_CHECK&&DDR_CTRL_RLAST_0==1&&DDR_CTRL_RVALID_0==1)begin
		check_addr <= check_addr+ADDR_OFFSET;
	end else begin 
		check_addr <= check_addr;
	end 
end 
//check_addr

always @(posedge clk )begin 
	if(reset_done_t1==0)begin	
		init_done_flag<=0;
	end else if(C_STATE == INIT_DONE)begin
		init_done_flag<=1;
	end else if(check_addr[`DDR3ADDRE_MAXBIT:0]>(STOP_ADDR-1-(ADDR_OFFSET<<1))&&DDR_CTRL_RLAST_0==1&&DDR_CTRL_RVALID_0==1)begin
		init_done_flag<=1;
	end else begin 
		init_done_flag<=init_done_flag;
	end 
end 
//init_done_flag

//
always @(posedge clk )begin 
	if(reset_done_t1==0)begin	
		check_done<=0;
	end else if(C_STATE == INIT_DONE)begin
		check_done<=1;
	end else if(C_STATE==INIT_CHECK&&rd_addr[`DDR3ADDRE_MAXBIT:0]>(STOP_ADDR-(ADDR_OFFSET<<1)-1))begin//&&DDR_CTRL_RLAST_0==1&&DDR_CTRL_RVALID_0==1
		check_done<=1;
	end else begin 
		check_done<=check_done;
	end 
end 
//check_done

always @(posedge clk )begin 
	if(C_STATE==INIT_DONE|reset_done_t1==0)begin 
		DDR_CLG_R_T1<=0;
	end else if (DDR_CLG_R_T0==0&&DDR_CLG_R==1&&C_STATE>3'b010)begin 
		DDR_CLG_R_T1<=1;
	end else begin 
		DDR_CLG_R_T1<=DDR_CLG_R_T1;
	end 
end 
//DDR_CLG_R_T1


always @(posedge clk)begin 
	if(wr_addr<rd_addr)begin 
		rema_num_temp<=0;
	end else begin
		rema_num_temp<= wr_addr-rd_addr;
	end 
end 
///rema_num_temp

always @(posedge clk)begin 
	
		rema_num<=rema_num_temp[`DDR3ADDRE_MAXBIT:0];
end 
//rema_num

always @(posedge clk)begin 
	if(rema_num<(ADDR_OFFSET<<1))begin 
		ddr_alempty<=1;
	end else begin 
		ddr_alempty<=0;
	end 
end 
//ddr_alempty

always @(posedge clk)begin
	if(rema_num>(`DDR3ADDRE_MAX-(ADDR_OFFSET<<1)))begin // //((STOP_ADDR-rema_num)<(ADDR_OFFSET<<2))
		ddr_alfull<=init_wrdone;//1
	end else begin 
		ddr_alfull<=0;
	end 
end 
//ddr_alfull

always @(posedge clk)begin
	if(rema_num>threshold_num)begin 
		ddr_pfull<=init_wrdone;//1
	end else begin
		ddr_pfull<=0;
	end 
end 
//ddr_pfull ddr programme full;if it goes high;ddr can receive only one frame data.

always @(posedge clk)begin 
	if(ddr_state_rst_t1)begin 
		wr_addr <= `START_ADDR_0;
	end else if(C_STATE==INIT_DONE)begin
		wr_addr <=0;//ADDR_OFFSET
	end else if(DDR_CTRL_AVALID_0&DDR_CTRL_ATYPE_0)begin 
		wr_addr <= wr_addr+ADDR_OFFSET;
	end else begin 
		wr_addr <= wr_addr ;
	end 
end 
//wr_addr

always @(posedge clk )begin 
	if(C_STATE == INIT_WRITE||C_STATE==PRE_WRRTE||C_STATE==STATE_WRRTE)begin 
		 DDR_CTRL_ATYPE_0<=1'b1;
		 DDR_CTRL_AADDR_0<=wr_addr[`DDR3ADDRE_MAXBIT:0];
	end else begin 
		 DDR_CTRL_ATYPE_0<=0;   
		 DDR_CTRL_AADDR_0<=rd_addr[`DDR3ADDRE_MAXBIT:0];     
	end 
end 
//DDR_CTRL_ATYPE_0 DDR_CTRL_AADDR_0  

always @(posedge clk)begin 
	if(reset_done_t1==0|(DDR_CTRL_WLAST_0==1&DDR_CTRL_WREADY_0==1))begin//DDR_CTRL_BVALID_0  //reset_done_t1==0|DDR_CTRL_WLAST_0==1
		wr_cycle <= 0;
	end else if((C_STATE==STATE_WRRTE&&DDR_CTRL_AREADY_0==1)||(C_STATE==INIT_WRITE&&DDR_CTRL_AREADY_0==1&&init_wrdone==0))begin		
		wr_cycle <= 1;		
	end else begin 
		wr_cycle <= wr_cycle;
	end 
end 
//wr_cycle

always @(posedge clk)begin
	 if(wr_cycle)begin
	 	if(wrfifo_rden)begin
			wr_cnt <= wr_cnt+1;		
		end else begin 
			wr_cnt <= wr_cnt;
		end 
	end else begin 
		wr_cnt <= 0;
	end 
end 
//wr_cnt

always @(posedge clk)begin
	if(!reset_done_t1)begin 
		wrfifo_rdreq <= 0;
	end else if((wr_cnt>=`ALEN_0-1)&&DDR_CTRL_WREADY_0==1)begin
		wrfifo_rdreq <= 0;
	end else if(wr_cycle&&DDR_CTRL_AVALID_0)begin/// (wr_cycle)
		wrfifo_rdreq<=1;
	end else begin 
		wrfifo_rdreq <= wrfifo_rdreq;
	end 
end 
//wrfifo_rdreq	


assign wrfifo_rden=wrfifo_rdreq&DDR_CTRL_WREADY_0;
//wrfifo_rden

always @(posedge clk)begin
	if((wr_cnt==(`ALEN_0)&&DDR_CTRL_WREADY_0==1)||(reset_done_t1==0))begin
		DDR_CTRL_WLAST_0<=0;
	end else if(wr_cnt==(`ALEN_0-1)&&wrfifo_rden==1)begin 
		DDR_CTRL_WLAST_0<=1;
	end else begin 
		DDR_CTRL_WLAST_0<=DDR_CTRL_WLAST_0;
	end 
//	DDR_CTRL_WLAST_0 <= (wr_cnt==(`ALEN_0-1)&&wrfifo_rden==1);
end 


always @(posedge clk)begin
   if((DDR_CTRL_WLAST_0==1&DDR_CTRL_WREADY_0==1)|reset_done_t1==0)begin
		DDR_CTRL_WVALID_0<=1'b0;
	end else if(wrfifo_rden)begin
		DDR_CTRL_WVALID_0<=1'b1;		
	end else begin 
		DDR_CTRL_WVALID_0<=DDR_CTRL_WVALID_0;
	end 
end 

//DDR_CTRL_WVALID_0 

//always @(posedge clk)begin
//	if(C_STATE==INIT_WRITE)begin
//		if(DDR_CTRL_WREADY_0)begin
//		DDR_CTRL_WDATA_0<={~wr_cnt,  	~wr_cnt,  	~wr_cnt,  	~wr_cnt,  	~wr_cnt,  	~wr_cnt,  ~wr_cnt,  ~wr_cnt,
//						  	~wr_cnt,	~wr_cnt,	~wr_cnt,	~wr_cnt, 	~wr_cnt, 	~wr_cnt,  ~wr_cnt,  ~wr_cnt };
//		end else begin
//		DDR_CTRL_WDATA_0<=DDR_CTRL_WDATA_0;
//		end 	
//	end else if (DDR_CTRL_WREADY_0)begin 
//		DDR_CTRL_WDATA_0 <=wrfifo_rdata;
//	end else begin 
//		DDR_CTRL_WDATA_0 <=DDR_CTRL_WDATA_0;
//	end 
//end 



always @ (posedge clk )begin
	if(wrfifo_rden)begin
		WrCheckBit <= ~WrCheckBit;
	end else begin 
		WrCheckBit <= WrCheckBit;
	end 
end 
//WrCheckBit
		
always @(posedge clk)begin
	if(C_STATE==INIT_WRITE&&DDR_CTRL_WREADY_0==1)begin		
		DDR_CTRL_WDATA_0[63:0]<={64{WrCheckBit}};	
	end else if (DDR_CTRL_WREADY_0)begin 
		DDR_CTRL_WDATA_0 <=wrfifo_rdata;
	end else begin 
		DDR_CTRL_WDATA_0 <=DDR_CTRL_WDATA_0;
	end 
end 

//DDR_CTRL_WDATA_0 <=wrfifo_rdata;


//*************************************read /init check*****************************************************
always @(posedge clk)begin 
	if(ddr_state_rst_t1)begin 
		rd_addr <= `START_ADDR_0;
	end else if(C_STATE==INIT_DONE)begin
		rd_addr <=0;
	end else if(DDR_CTRL_AVALID_0==1&DDR_CTRL_ATYPE_0==0)begin 
		rd_addr <= rd_addr+ADDR_OFFSET;
	end else begin 
		rd_addr <= rd_addr ;
	end 
end 
//rd_addr




always @(posedge clk)begin 
	if(reset_done_t1==0||ddrctrl_avalid_rd==1||C_STATE==INIT_DONE)begin
		rd_cycle <= 0;
	end else if((C_STATE==STATE_READ)||(C_STATE==INIT_CHECK&&check_done==0))begin		
		rd_cycle <= 1;		
	end else begin 
		rd_cycle <= rd_cycle;
	end 
end 

//rd_cycle


always @ (posedge clk )begin 
	if(reset_done_t1==0)begin 
		ddrctrl_avalid_rd<=0;
	end else if(ddrctrl_avalid_rd==0&&rd_cycle==1&&DDR_CTRL_AREADY_0==1)begin//&&C_STATE==STATE_READ
		ddrctrl_avalid_rd<=1;
	end else begin 
		ddrctrl_avalid_rd<=0;
	end 
end 
//ddrctrl_avalid_rd



//always @(posedge clk)begin
//	if(DDR_CTRL_RVALID_0&&C_STATE==INIT_CHECK)begin  //DDR_CTRL_RVALID_0
//			if(DDR_CTRL_RDATA_0!={	~rd_cnt, ~rd_cnt,  ~rd_cnt,  ~rd_cnt,  ~rd_cnt,  ~rd_cnt,  ~rd_cnt,  ~rd_cnt,
//						   			~rd_cnt, ~rd_cnt,  ~rd_cnt,  ~rd_cnt,  ~rd_cnt,  ~rd_cnt,  ~rd_cnt,  ~rd_cnt })begin
//				
//				check_err<=1'b1;
//			end else begin
//				check_err<=0;
//			end 
//	end else begin 
//		check_err <=0;
//	end 
//end 
//check_err

always @ (posedge clk )begin
	if(DDR_CTRL_RVALID_0)begin
		RdCheckBit <= ~RdCheckBit;
	end else begin 
		RdCheckBit <= RdCheckBit;
	end 
end 
//WrCheckBit

always @(posedge clk)begin
	if(C_STATE==INIT_CHECK&&(DDR_CTRL_RDATA_0[63:0]!={64{RdCheckBit}}))begin  //DDR_CTRL_RVALID_0
			
		check_err1<=DDR_CTRL_RVALID_0;
			
	end else begin 
		check_err1 <=0;
	end 
end 
//check_err1

//always @(posedge clk)begin
//	if(C_STATE==INIT_CHECK&&(DDR_CTRL_RDATA_0[127:64]!={64{RdCheckBit}}))begin  //DDR_CTRL_RVALID_0
//			
//		check_err2<=DDR_CTRL_RVALID_0;
//			
//	end else begin 
//		check_err2 <=0;
//	end 
//end
////check_err2

always @ (posedge clk )begin
	check_err <= check_err1;//|check_err2;
end  
//check_err

always @(posedge clk )begin 
	if(reset_done_t1==0)begin
		check_fail<=0;
	end else if(check_err)begin 
		check_fail<=1;
	end else begin 
		check_fail <= check_fail;
	end
end 
//check_fail;


//

  
  
//************rd_clk**********************

always @(posedge rd_clk)begin 
	if(rdfifo_empty==0&fx3_full==0&rddr3_en==1)begin		
		rdfifo_rden<=1;
	end else begin 
		rdfifo_rden<=0;
	end 
end 
//rdfifo_rden

always@ (posedge rd_clk)begin 
	rddr3_vld <= rdfifo_empty==0&rdfifo_rden==1;
end 
//rddr3_vld

//************************************test  ************************************************************

`ifdef DDRTEST_BW

reg [`DDR3ADDRE_MAXBIT:0]	checkerr_cnt	=0;   
reg 	   					ddr_verify_err	=0;
reg 	   					ddr_verify_st	=0;

reg [26:0] 					cnt1s 		    =0;
reg [31:0] 					data_num_wr		=0;
reg [31:0] 					data_num_rd 	=0;	
reg 	   					s1_flag			=0;
reg [7:0]					rd_cnt			=0	;
reg [7:0] 					DataRdTimeOut   = 8'hff ;
reg       					DataRdReadyClr  = 1'h0  ;
reg 						DataRdTimeOut_flag =0   ;

always @ (posedge clk )begin
	if(ddr_state_rst_t1)begin
		ddr_verify_st <= 1'b0;
	end else if(DDR_CTRL_RVALID_0)begin
		ddr_verify_st <=1'b1;
	end else begin 
		ddr_verify_st<=ddr_verify_st;
	end 
end 
//ddr_verify_st
always @(posedge clk )begin
	if(ddr_verify_st==1&&DDR_CTRL_RVALID_0==1&&DDR_CTRL_RDATA_0[15:0]<65533)begin
			if(DDR_CTRL_RDATA_0[15:0]-DDR_CTRL_RDATA_0[79:64]==1'b1)begin
				ddr_verify_err<=1'b0;
			end else begin 
				ddr_verify_err<=1'b1;
			end 
	end else begin 
		ddr_verify_err <= 1'b0;
	end 
end 
//ddr_verify_err


always @(posedge clk )begin
	if (cnt1s[26]==1&&cnt1s[25]==1)begin //100ms
			s1_flag<=1;
	end else begin 
			s1_flag<=0;
	end 
end 
//s1_flag

always @ (posedge clk )begin
	
	if (s1_flag)begin //100ms
		cnt1s<=0;
	end else  begin 
		cnt1s<=cnt1s+1;
	end 
	
end 
//cnt100ms



always @ (posedge clk )begin 
	if(s1_flag)begin 
		data_num_wr<=0;
	end else  if(DDR_CTRL_WREADY_0&DDR_CTRL_WVALID_0)begin
		data_num_wr<=data_num_wr+1;
	end else begin 
		data_num_wr<=data_num_wr;
	end 
end 
//data_num_wr//128bit


always @ (posedge clk )begin 
	if(s1_flag)begin 
		data_num_rd<=0;
	end else  if(DDR_CTRL_RVALID_0)begin
		data_num_rd<=data_num_rd+1;
	end else begin 
		data_num_rd<=data_num_rd;
	end 
end 
//data_num_wr//128bit


always @(posedge clk)begin
	if(reset_done_t1==0)begin 
		checkerr_cnt <= 0;
	end else if(check_err)begin 
		checkerr_cnt<=checkerr_cnt+1'b1;
	end else begin 
		checkerr_cnt <=checkerr_cnt;
	end 
end 
//checkerr_cnt

always @(posedge clk)begin 
	if(reset_done_t1==0||(DDR_CTRL_RLAST_0==1&DDR_CTRL_RVALID_0==1)||(C_STATE==INIT_DONE))begin
		rd_cnt <= 0;
	end else if(DDR_CTRL_RVALID_0)begin
		rd_cnt <= rd_cnt + 1 ;
	end else begin 
		rd_cnt <= rd_cnt;
	end 
end 
//rd_cnt


  always @( posedge clk)
  begin
  if(C_STATE==STATE_READ&&DDR_CTRL_RVALID_0==0)  DataRdTimeOut <=  DataRdTimeOut - {7'h0, (|DataRdTimeOut)};
  else DataRdTimeOut <= 8'hff;
  end

  always @( posedge clk)  DataRdReadyClr <=  (DataRdTimeOut == 5'h1);
  
  always @(posedge clk )  begin 
  	if(ddr_state_rst_t1) DataRdTimeOut_flag<=0;
  	else if(DataRdReadyClr) DataRdTimeOut_flag<=1;
  	else  DataRdTimeOut_flag <=DataRdTimeOut_flag;
  end 
`endif

//****************************DDR STATE *******************************************************************
always @(posedge clk)begin 
	if( slip_check_d==1 )begin //reset all//  |DataRdReadyClr==1
		C_STATE<=INIT_DONE;
	end else if(reset_done_t1==0 )begin//DDR RESET 
		C_STATE<=IDLE;
	end else if((DDR_CLG_R_T1==1&&C_STATE==PRE_WRRTE)||(DDR_CLG_R_T1==1&&C_STATE==PRE_READ))begin//DDR CLEAR
		C_STATE<=INIT_DONE;
	end else begin 
		C_STATE<=N_STATE;
	end 
end 
//C_STATE	


always @( * ) begin //*
	case(C_STATE)
	IDLE:	begin//0
				if(DDR_CTRL_AREADY_0)begin 
					N_STATE<=INIT_WRITE;
				end else begin 
					N_STATE<=IDLE;
				end 
	end 
	
	INIT_WRITE:begin //1
				if(init_wrdone)begin 
					N_STATE<=INIT_CHECK;
				end else begin 
					N_STATE<=INIT_WRITE;
				end 
	end 
	
	INIT_CHECK:begin //2
				if(init_done_flag==1)begin//&&(check_fail==0) //init_done_flag =1 //check_done==1
					N_STATE<=INIT_DONE;
				end else begin 
					N_STATE<=INIT_CHECK;
				end 
	end 
	
	INIT_DONE:begin//3
				if(DDR_CTRL_AREADY_0)begin 
					N_STATE<=PRE_WRRTE;
				end else begin 
					N_STATE<=INIT_DONE;
				end 
	end 
	
	PRE_WRRTE:begin //4
				if(ddr_alfull==1)begin//if ddr full ,jump to read  //&&wr_cycle==0
					N_STATE<=PRE_READ;
				end else if (wrfifo_count<(`ALEN_0+1)&&wrfifo_full==0)begin //if write fifo do not have data;jump to read //wrfifo_pflag==0
					N_STATE<=PRE_READ;
				end else begin 
					N_STATE<=STATE_WRRTE;
				end 
		
	end 
	
	STATE_WRRTE:begin//5
				if (DDR_CTRL_WLAST_0&DDR_CTRL_WREADY_0)begin //if write cycle done,jump to read //DDR_CTRL_BVALID_0 //DDR_CTRL_WLAST_0
					N_STATE<=PRE_READ;
				end else begin 
					N_STATE<=STATE_WRRTE;
				end 
	end 
	PRE_READ:begin //6
				if(ddr_alempty==1)begin //if ddr empty ,jump to write  
					N_STATE<=PRE_WRRTE;
				end else if(rdfifo_count>RDFIFO_COUNT_END||rdfifo_full==1)begin // if read fifo have a lot of data ;jumo to  write //rdfifo_pflag==1
					N_STATE<=PRE_WRRTE;				
				end else begin
					N_STATE<=STATE_READ;
				end 
		
	end 
	
	STATE_READ:begin //7
			    if (ddrctrl_avalid_rd)begin//if read cycle done ,jump to write ddrctrl_avalid_rd //DDR_CTRL_RLAST_0&&DDR_CTRL_RVALID_0
					N_STATE<=PRE_WRRTE;
				end else begin 
					N_STATE<=STATE_READ;
				end 
	end 
	
	default:begin 
		N_STATE<=IDLE;
	end 
	
	endcase
end 





wrddr3_fifo 	u_wrddr3_fifo(  
	
	.wr_clk_i 		( wr_clk 			),//
	.rd_clk_i 		( clk 				),//
	.wr_en_i 		( wrddr3_en 		),//
	.rd_en_i 		( wrfifo_rden 		),//
	.a_rst_i 		( ddr_state_rst_t1|~init_done_flag ),//~init_done_flag ~check_done
	.wdata 			( wrddr3_data 		),//
	
	.full_o 		( wrfifo_full 		),//
	.empty_o 		(  					),
	.rdata 			( wrfifo_rdata 		),//
	.wr_datacount_o ( 				 	),
	.rd_datacount_o ( wrfifo_count 		),//
	.rst_busy 		( 		 			)

);


rdddr3_fifo 	u_rdddr3_fifo(
	
	.wr_clk_i		( clk 				),//
	.rd_clk_i 		( rd_clk 			),//
	.wr_en_i 		( DDR_CTRL_RVALID_0 ),//
	.rd_en_i 		( rdfifo_rden 		),//
	.a_rst_i 		( ddr_state_rst_t1|~init_done_flag ),//reset the FIFO if check_done ==0;//~init_done_flag ~check_done
	.wdata 			( DDR_CTRL_RDATA_0 	),//
	
	.full_o 		( rdfifo_full 		),//
	.empty_o		( rdfifo_empty 		),
	.rdata 			( rddr3_data 		),//
	.wr_datacount_o ( rdfifo_count		),//
	.rd_datacount_o ( 					),
	.rst_busy 		( 		 		 	)

);

////wire [31:0] CRC32;
////
//// CRC32	CRC32_INST(
//// 
////         .data_in	(DDR_CTRL_RDATA_0), // input [127:0] 
////         .crc_en	(DDR_CTRL_RVALID_0), // input         
////         .crc_out	(CRC32), // output [31:0] 
////         .rst		(!reset_done_t1), // input         
////         .clk       (clk)  // input  
////                
////        );
////        




//verify_err
endmodule 