`timescale 1ns / 1ps
//-------------------------------------------------------------------------------
// Company:  QHYCCD
// Engineer: YangSK
// 
// Create Date: 2022/5/13
// Design Name: T35_TOP
// Module Name: Ddr3Mig_Top
// Project Name: T35_FRAMEWORK
// Target Devices: t35f324
// Tool Versions: EFINITY21.2
// Description: : ddr3 :MT41K256M16TW-107:P£»  1.07ns @ CL = 13 (DDR3-1866) -107  ; row 15bit ;  colum 10bit  bank 3bit
// Dependencies:  DDR3 ADDRESS[27:0] =2^28*16/1024/1024/1024=4Gbit; AXI ADDRESS is [28:0];every address is 8bit data; 0-1fff_ffff
// 
// Revision:rev1
// 
// Additional Comments:
// 
//--------------------------------------------------------------------------------

module Ddr3Mig_Top(

		input	wire						clk					,//100M  syspll_CLKOUT100
		input	wire						clk_low				,//2Mhz -8Mhz  
		input	wire						rstn				,//active low
		input	wire						DDR_CLG_R 			,
		input	wire						pll_locked 			,		
		input   wire      					pll_ddr_locked 		,  
		input	wire						skip_check			,
//ddr3 signals		
        input	wire						wr_clk				,                                               
        input	wire	[63:0]				wrddr3_data			,                                               
        input	wire						wrddr3_en			,                                               
        input	wire						rd_clk				,                                               
        input	wire						rddr3_en			,                                               
        input	wire						fx3_full			,                                               
        input   wire    [`DDR3ADDRE_MAXBIT:0]	threshold_num		,                                               
        output	wire	[63:0]				rddr3_data			,                                               
        output	wire						rddr3_vld			,                                               
                                                        
//ddr3 state	
		output	wire	[`DDR3ADDRE_MAXBIT:0]	rema_num			,			                                                        
        output	wire	[7:0]					ddr_code			, //{DataRdTimeOut_flag£¬ddr_pfull,ddr_alempty,ddr_alfull,addr_err,check_fail,check_done};                                                                                                                                                                                                            
//DDR hardcore signals
		//input 	wire						DDR_CTRL_CFG_SDA_OEN,
 		//output 	wire						DDR_CTRL_CFG_SCL_IN	,
  		//output 	wire						DDR_CTRL_CFG_SDA_IN	,
  		
  		output 	wire						DDR_CTRL_CFG_SEQ_RST,
  		output  wire						DDR_CTRL_CFG_SEQ_START,
    	output 	wire						DDR_CTRL_CFG_RST_N	,
	                            			
  		input 								DDR_CTRL_AREADY_0	,  //**Address ready.
  		input [7:0] 						DDR_CTRL_BID_0		,  //Response ID tag. This signal is the ID tag of the write response.// not use
  		input 								DDR_CTRL_BVALID_0	,  //Write response valid. This signal indicates that the channel is signaling a valid write response.                  
  		input [127:0] 						DDR_CTRL_RDATA_0	,  //**Read data.              
  		input [7:0] 						DDR_CTRL_RID_0		,  //Read ID tag. This signal is the identification tag for the read data group of signals generated by the slave. not user       
  		input 								DDR_CTRL_RLAST_0	,  //**Read last. This signal indicates the last transfer in a read burst.                      
  		input [1:0] 						DDR_CTRL_RRESP_0	,  //Read response. This signal indicates the status of the read transfer
  		input 								DDR_CTRL_RVALID_0	,  //**Read valid
  		input 								DDR_CTRL_WREADY_0	,  //**Write ready. This signal indicates that the slave can accept the write data.
  		                		                                                                                          
  		output [31:0] 						DDR_CTRL_AADDR_0	,  //** Address. ATYPE defines whether it is a read or write address. It gives the address of the first transfer in a burst transaction. 
  		output [1:0] 						DDR_CTRL_ABURST_0	,  // Burst type. The burst type and the size determine how the address  for each transfer within the burst is calculated.               
  		output [7:0] 						DDR_CTRL_AID_0		,  // Address ID. This signal identifies the group of address signals. Depends on ATYPE, the ID can be for a read or write address group             
  		output [7:0] 						DDR_CTRL_ALEN_0		,  // Burst length. This signal indicates the number of transfers in a burst
  		output [1:0] 						DDR_CTRL_ALOCK_0	,  // Lock type. This signal provides additional information about the  atomic characteristics of the transfer  
  		output [2:0] 						DDR_CTRL_ASIZE_0	,  // Burst size. This signal indicates the size of each transfer in the burst.                       
  		output 								DDR_CTRL_ATYPE_0	,  //** This signal distinguishes whether is it is a read or write operation. 0= read and 1 = write.
  		output 								DDR_CTRL_AVALID_0	,  //** Address valid. This signal indicates that the channel is signaling valid address and control information.                                                
  		output 								DDR_CTRL_BREADY_0	,  // Response ready. This signal indicates that the master can accept a write response                            
  		output 								DDR_CTRL_RREADY_0	,  //** Read ready. This signal indicates that the master can accept the read data and response information.                                              
  		output [127:0] 						DDR_CTRL_WDATA_0	,  //** Write data.
  		output [7:0] 						DDR_CTRL_WID_0		,  // Write ID tag. This signal is the ID tag of the write data transfer
  		output 								DDR_CTRL_WLAST_0	,  //** Write last. This signal indicates the last transfer in a write burst
  		output [15:0] 						DDR_CTRL_WSTRB_0	,  // Write strobes. This signal indicates which byte lanes hold valid data. There is one write strobe bit for each eight bits of the write data bus  
  		output 								DDR_CTRL_WVALID_0      //** Write valid. This signal indicates that valid write data and strobes are  available   
	                                 

);

wire[24:0]				err_cnt			;
wire					checker_start	;
wire					checker_fail	;
wire					checker_done	;
wire					ddr_reset_done	;

//  assign DDR_CTRL_CFG_RST_N =~rst;  
//  wire			ddr_cal_auto_en			;
//  wire[3:0]		ddr_cal_auto_sel		;//bit0 read leveling  ;bit1 gate leveling; bit2 write leveling;  
//  wire [7:0]	ddr_cal_auto_status		;
//  wire			auto_cal_done			;
//  wire			auto_cal_err			;
  
//ddr3_calibration 	u_ddr3_calibration(
//
//.rst_n 					( ~rst 					),
//.clk 					( clk_low 				),//2-8Mhz
//.ddr_cal_auto_en 		( test_start 			),// ddr_cal_auto_en
//.ddr_cal_auto_sel 		( 4'b0010		 		),//bit0 read leveling  ;bit1 gate leveling; bit2 write leveling; 
//.pll_locked 			( pll_locked 			),
//.pll_ddr_locked 		( pll_ddr_locked 		),
//.ddr_slave_i2c_sda_in 	( DDR_CTRL_CFG_SDA_OEN  ),   
//
//.pll_rst_n 				(  						),
//.pll_ddr_rst_n 			(  						),
//.ddr_cal_auto_status 	( ddr_cal_auto_status 	),
//.auto_cal_done 			( auto_cal_done 		),
//.auto_cal_err 			( auto_cal_err 			),
//.ddr_slave_i2c_scl 		( DDR_CTRL_CFG_SCL_IN 	),
//.ddr_slave_i2c_sda 		( DDR_CTRL_CFG_SDA_IN 	)
//
//);

ddr_reset_control 		u_ddr_reset_control(

.ddr_rstn_i 					( rstn 	    			),
.clk 							( clk					),

.ddr_rstn 						( DDR_CTRL_CFG_RST_N 	),
.ddr_cfg_seq_rst 				( DDR_CTRL_CFG_SEQ_RST 	),
.ddr_cfg_seq_start			    ( DDR_CTRL_CFG_SEQ_START),
.ddr_init_done 					( ddr_reset_done 		)

);

//reg [31:0]					resetcnt		=0;
//
//always @ (posedge clk )begin 
//	if(ddr_code[0]==0&rstn==1)begin 
//		resetcnt <= resetcnt + 1;
//	end else begin 
//		resetcnt <= 0;
//	end 
//end 
////resetcnt 


 ddr3_state  ddr3_state_inst(

		.clk					(clk				),
		.reset_done				(ddr_reset_done		),
		.DDR_CLG_R				(DDR_CLG_R			),
		.ddrpll_locked			(pll_ddr_locked		),
		.skip_check				(skip_check			),
	                  
		.wr_clk					(wr_clk			    ),
		.wrddr3_data			(wrddr3_data		),
		.wrddr3_en				(wrddr3_en		    ),
		.rd_clk					(rd_clk			    ),
		.rddr3_en				(rddr3_en		    ),//
		.fx3_full				(fx3_full		    ),	
		.threshold_num			(threshold_num	    ),//unit: byte			
		.rddr3_data				(rddr3_data		    ),
		.rddr3_vld				(rddr3_vld		    ),
		                                                        
		//ddr3 state signals		                            
		.rema_num				(rema_num			),//unit:byte £¬set it to 256bit
		.ddr_code 				(ddr_code			),//{DataRdTimeOut_flag£¬ddr_pfull,ddr_alempty,ddr_alfull,addr_err,check_fail,init_done_flag};                                                               
		
		//ddr axi signals				                            
		.DDR_CTRL_AREADY_0		(DDR_CTRL_AREADY_0	),  //**Address ready.
  		.DDR_CTRL_BID_0			(DDR_CTRL_BID_0		), 
  		.DDR_CTRL_BVALID_0		(DDR_CTRL_BVALID_0	),  //Write response valid. This signal indicates that the channel is signaling a valid write response.                  
  		.DDR_CTRL_RDATA_0		(DDR_CTRL_RDATA_0	),  //**Read data.              
  		.DDR_CTRL_RID_0			(DDR_CTRL_RID_0		),
  		.DDR_CTRL_RLAST_0		(DDR_CTRL_RLAST_0	),  //**Read last. This signal indicates the last transfer in a read burst.                      
  		.DDR_CTRL_RRESP_0		(DDR_CTRL_RRESP_0	),  //Read response. This signal indicates the status of the read transfer
  		.DDR_CTRL_RVALID_0		(DDR_CTRL_RVALID_0	),  //**Read valid
  		.DDR_CTRL_WREADY_0		(DDR_CTRL_WREADY_0	),  //**Write ready. This signal indicates that the slave can accept the write data.
  		                		                                                                                         
  		.DDR_CTRL_AADDR_0		(DDR_CTRL_AADDR_0	 ),  //** Address. ATYPE defines whether it is a read or write address. It gives the address of the first transfer in a burst transaction. 
  		.DDR_CTRL_ABURST_0		(DDR_CTRL_ABURST_0	 ),  // Burst type. The burst type and the size determine how the address  for each transfer within the burst is calculated.               
  		.DDR_CTRL_AID_0			(DDR_CTRL_AID_0		 ),  // Address ID. This signal identifies the group of address signals. Depends on ATYPE, the ID can be for a read or write address group             
  		.DDR_CTRL_ALEN_0		(DDR_CTRL_ALEN_0	 ),  // Burst length. This signal indicates the number of transfers in a burst
  		.DDR_CTRL_ALOCK_0		(DDR_CTRL_ALOCK_0	 ),  // Lock type. This signal provides additional information about the  atomic characteristics of the transfer  
  		.DDR_CTRL_ASIZE_0		(DDR_CTRL_ASIZE_0	 ),  // Burst size. This signal indicates the size of each transfer in the burst.                       
  		.DDR_CTRL_ATYPE_0		(DDR_CTRL_ATYPE_0	 ),  //** This signal distinguishes whether is it is a read or write operation. 0= read and 1 = write.
  		.DDR_CTRL_AVALID_0		(DDR_CTRL_AVALID_0	 ),  //** Address valid. This signal indicates that the channel is signaling valid address and control information.                                                
  		.DDR_CTRL_BREADY_0		(DDR_CTRL_BREADY_0	 ),  // Response ready. This signal indicates that the master can accept a write response                            
  		.DDR_CTRL_RREADY_0		(DDR_CTRL_RREADY_0	 ),  //** Read ready. This signal indicates that the master can accept the read data and response information.                                              
  		.DDR_CTRL_WDATA_0		(DDR_CTRL_WDATA_0	 ),  //** Write data.
  		.DDR_CTRL_WID_0			(DDR_CTRL_WID_0		 ),  // Write ID tag. This signal is the ID tag of the write data transfer
  		.DDR_CTRL_WLAST_0		(DDR_CTRL_WLAST_0	 ),  //** Write last. This signal indicates the last transfer in a write burst
  		.DDR_CTRL_WSTRB_0		(DDR_CTRL_WSTRB_0	 ),  // Write strobes. This signal indicates which byte lanes hold valid data. There is one write strobe bit for each eight bits of the write data bus  
  		.DDR_CTRL_WVALID_0   	(DDR_CTRL_WVALID_0   )   //** Writ

);

//assign checker_start= test_start;
//
//
// ddrmemory_checker #(
//         
//    .AXIDATA_WIDTH 	 				(127				)	,//e.g. 127 is [127:0]  
//	.ALEN 			 				(7  				)	,//e.g. 7 is butst Transmission 8 times
//	.ASIZE 			 				(4 					)	,//4 is 2^4 = 16bytes ,
//	.START_ADDR 	 				(32'h00000000		)	, 
//	.STOP_ADDR 		 				(32'h1FFFFF7F		)	
//	
//)ddrmemory_checker_inst
//(
//
//  
//	.axi_clk						(clk				),
//	.rstn							(~rst				),//active low  ,default0
//	.start							(checker_start		),//rige edge start 
//	.fail							(checker_fail		),
//	.done							(checker_done		),
//	.err_cnt						(err_cnt			),
//	                    			                                 	                                                     
//	.aready							(DDR_CTRL_AREADY_0	),
//	.aid							(DDR_CTRL_AID_0		),
//	.aaddr							(DDR_CTRL_AADDR_0	),
//	.alen							(DDR_CTRL_ALEN_0	),
//	.asize							(DDR_CTRL_ASIZE_0	),
//	.aburst							(DDR_CTRL_ABURST_0	),
//	.alock							(DDR_CTRL_ALOCK_0	),
//	.avalid							(DDR_CTRL_AVALID_0	),
//	.atype							(DDR_CTRL_ATYPE_0	),
//                        			                                                                                             
//	.wready							(DDR_CTRL_WREADY_0	),		
//	.wid							(DDR_CTRL_WID_0		),
//	.wdata							(DDR_CTRL_WDATA_0	),
//	.wstrb							(DDR_CTRL_WSTRB_0	),
//	.wlast							(DDR_CTRL_WLAST_0	),
//	.wvalid							(DDR_CTRL_WVALID_0	),
//                        			                                                       		                                            
//	.rid							(DDR_CTRL_RID_0		),
//	.rresp							(DDR_CTRL_RRESP_0	),
//	.rdata							(DDR_CTRL_RDATA_0	),
//	.rlast							(DDR_CTRL_RLAST_0	),
//	.rvalid							(DDR_CTRL_RVALID_0	),
//	.rready							(DDR_CTRL_RREADY_0	),
//                        			
//	.bid							(DDR_CTRL_BID_0		),
//	.bvalid							(DDR_CTRL_BVALID_0	),
//	.bready							(DDR_CTRL_BREADY_0	)
//	     				    		                        		
//);	





endmodule