
// Efinity Top-level template
// Version: 2021.2.323.2.18
// Date: 2026-08-28 10:46

// Copyright (C) 2017 - 2021 Efinix Inc. All rights reserved.

// This file may be used as a starting point for Efinity synthesis top-level target.
// The port list here matches what is expected by Efinity constraint files generated
// by the Efinity Interface Designer.

// To use this:
//     #1)  Save this file with a different name to a different directory, where source files are kept.
//              Example: you may wish to save as G:\外触发小板子\T35_FRAMEWORK_V3_241225\T35_FRAMEWORK_V3_241225\T35_FRAMEWORK_V3\T35_FRAMEWORK.v
//     #2)  Add the newly saved file into Efinity project as design file
//     #3)  Edit the top level entity in Efinity project to:  T35_FRAMEWORK
//     #4)  Insert design content.


module T35_FRAMEWORK
(
  input ddrrefclk,
  input miso,
  input syspll_LOCKED,
  input ddrpll_LOCKED,
  input CMOSPLL_LOCKED,
  input CMOS_AMPV_IN,
  input CMOS_CTL1_IN,
  input CMOS_CTL2_IN,
  input CMOS_CTL3_IN,
  input CMOS_CTL4_IN,
  input CMOS_CTL5_IN,
  input CMOS_TECEN_IN,
  input CMOS_XCLR_IN,
  input CMOS_XHS_IN,
  input CMOS_XMASTER_IN,
  input CMOS_XTRIG_IN,
  input CMOS_XVS_IN,
  input I2CSCL_0,
  input I2CSDA_0_IN,
  input MUX_GPIO1_IN,
  input MUX_GPIO2_IN,
  input MUX_GPIO3_IN,
  input MUX_GPIO4_IN,
  input TP_GPIO5_IN,
  input TP_GPIO6_IN,
  input TP_GPIO7_IN,
  input TP_GPIO8_IN,
  input UART_FPGARX,
  input UART_FX3TX,
  input USB_RESET,
  input optic_trigin,
  input fx3_ctl1,
  input fx3_ctl4,
  input fx3_ctl5,
  input fx3_ctl6,
  input fx3_ctl7,
  input [3:0] mipi_rx_inst1_CNT,
  input [63:0] mipi_rx_inst1_DATA,
  input [17:0] mipi_rx_inst1_ERROR,
  input [3:0] mipi_rx_inst1_HSYNC,
  input [5:0] mipi_rx_inst1_TYPE,
  input [3:0] mipi_rx_inst1_ULPS,
  input mipi_rx_inst1_ULPS_CLK,
  input mipi_rx_inst1_VALID,
  input [1:0] mipi_rx_inst1_VC,
  input [3:0] mipi_rx_inst1_VSYNC,
  input sysclk,
  input syspll_CLKOUT25,
  input syspll_CLKOUT100,
  input CMOSPLL_CMOSCLKOUT,
  input cfg_ERROR,
  input DDR_CTRL_AREADY_0,
  input [7:0] DDR_CTRL_BID_0,
  input DDR_CTRL_BVALID_0,
  input [127:0] DDR_CTRL_RDATA_0,
  input [7:0] DDR_CTRL_RID_0,
  input DDR_CTRL_RLAST_0,
  input [1:0] DDR_CTRL_RRESP_0,
  input DDR_CTRL_RVALID_0,
  input DDR_CTRL_WREADY_0,
  output CS0,
  output HOLD_N,
  output WP_N,
  output mosi_OUT,
  output mosi_OE,
  output sclk,
  output CMOS_AMPV_OUT,
  output CMOS_AMPV_OE,
  output CMOS_CTL1_OUT,
  output CMOS_CTL1_OE,
  output CMOS_CTL2_OUT,
  output CMOS_CTL2_OE,
  output CMOS_CTL3_OUT,
  output CMOS_CTL3_OE,
  output CMOS_CTL4_OUT,
  output CMOS_CTL4_OE,
  output CMOS_CTL5_OUT,
  output CMOS_CTL5_OE,
  output CMOS_TECEN_OUT,
  output CMOS_TECEN_OE,
  output CMOS_XCLR_OUT,
  output CMOS_XCLR_OE,
  output CMOS_XHS_OUT,
  output CMOS_XHS_OE,
  output CMOS_XMASTER_OUT,
  output CMOS_XMASTER_OE,
  output CMOS_XTRIG_OUT,
  output CMOS_XTRIG_OE,
  output CMOS_XVS_OUT,
  output CMOS_XVS_OE,
  output CS1,
  output I2CSDA_0_OUT,
  output I2CSDA_0_OE,
  output LED_B,
  output LED_G,
  output LED_R,
  output MUX_GPIO1_OUT,
  output MUX_GPIO1_OE,
  output MUX_GPIO2_OUT,
  output MUX_GPIO2_OE,
  output MUX_GPIO3_OUT,
  output MUX_GPIO3_OE,
  output MUX_GPIO4_OUT,
  output MUX_GPIO4_OE,
  output TP_GPIO5_OUT,
  output TP_GPIO5_OE,
  output TP_GPIO6_OUT,
  output TP_GPIO6_OE,
  output TP_GPIO7_OUT,
  output TP_GPIO7_OE,
  output TP_GPIO8_OUT,
  output TP_GPIO8_OE,
  output UART_FPGATX,
  output UART_FX3RX,
  output fx3_resetn,
  output optic_trigout,
  output fx3_ctl11,
  output fx3_ctl12,
  output [31:0] fx3_data,
  output mipi_rx_inst1_CLEAR,
  output mipi_rx_inst1_DPHY_RSTN,
  output [1:0] mipi_rx_inst1_LANES,
  output mipi_rx_inst1_RSTN,
  output [3:0] mipi_rx_inst1_VC_ENA,
  output [1:0] cfg_CBSEL,
  output cfg_CONFIG,
  output cfg_ENA,
  output [31:0] DDR_CTRL_AADDR_0,
  output [1:0] DDR_CTRL_ABURST_0,
  output [7:0] DDR_CTRL_AID_0,
  output [7:0] DDR_CTRL_ALEN_0,
  output [1:0] DDR_CTRL_ALOCK_0,
  output [2:0] DDR_CTRL_ASIZE_0,
  output DDR_CTRL_ATYPE_0,
  output DDR_CTRL_AVALID_0,
  output DDR_CTRL_BREADY_0,
  output DDR_CTRL_CFG_SEQ_RST,
  output DDR_CTRL_CFG_SEQ_START,
  output DDR_CTRL_RREADY_0,
  output DDR_CTRL_CFG_RST_N,
  output [127:0] DDR_CTRL_WDATA_0,
  output [7:0] DDR_CTRL_WID_0,
  output DDR_CTRL_WLAST_0,
  output [15:0] DDR_CTRL_WSTRB_0,
  output DDR_CTRL_WVALID_0
);


endmodule

