
# Efinity Interface Designer SDC
# Version: 2021.2.323.2.18
# Date: 2026-08-28 10:46

# Copyright (C) 2017 - 2021 Efinix Inc. All rights reserved.

# Device: T35F324
# Project: T35_FRAMEWORK
# Timing Model: I4 (final)

# PLL Constraints
#################
create_clock -period 10.00 syspll_CLKOUT100
create_clock -period 40.00 syspll_CLKOUT25
create_clock -period 2.50 ddrpll_CLKOUT
create_clock -period 37.04 CMOSPLL_CMOSCLKOUT

# GPIO Constraints
####################
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {ddrrefclk}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {ddrrefclk}]
set_input_delay -clock syspll_CLKOUT25 -max 5.168 [get_ports {miso}]
set_input_delay -clock syspll_CLKOUT25 -min 2.584 [get_ports {miso}]
create_clock -period <USER_PERIOD> [get_ports {sysclk}]
set_output_delay -clock syspll_CLKOUT25 -max -3.700 [get_ports {CS0}]
set_output_delay -clock syspll_CLKOUT25 -min -2.071 [get_ports {CS0}]
set_output_delay -clock syspll_CLKOUT25 -max -3.700 [get_ports {HOLD_N}]
set_output_delay -clock syspll_CLKOUT25 -min -2.071 [get_ports {HOLD_N}]
set_output_delay -clock syspll_CLKOUT25 -max -3.700 [get_ports {sclk}]
set_output_delay -clock syspll_CLKOUT25 -min -2.071 [get_ports {sclk}]
set_output_delay -clock syspll_CLKOUT25 -max -3.700 [get_ports {WP_N}]
set_output_delay -clock syspll_CLKOUT25 -min -2.071 [get_ports {WP_N}]
set_output_delay -clock syspll_CLKOUT25 -max -3.700 [get_ports {mosi_OUT}]
set_output_delay -clock syspll_CLKOUT25 -min -2.071 [get_ports {mosi_OUT}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {mosi_OE}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {mosi_OE}]

# LVDS RX GPIO Constraints
############################
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {I2CSCL_0}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {I2CSCL_0}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {optic_trigin}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {optic_trigin}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {UART_FPGARX}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {UART_FPGARX}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {UART_FX3TX}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {UART_FX3TX}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {USB_RESET}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {USB_RESET}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CS1}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CS1}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_resetn}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_resetn}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {LED_B}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {LED_B}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {LED_G}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {LED_G}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {LED_R}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {LED_R}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {optic_trigout}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {optic_trigout}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {UART_FPGATX}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {UART_FPGATX}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {UART_FX3RX}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {UART_FX3RX}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_AMPV_IN}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_AMPV_IN}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_AMPV_OUT}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_AMPV_OUT}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_AMPV_OE}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_AMPV_OE}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_CTL1_IN}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_CTL1_IN}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_CTL1_OUT}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_CTL1_OUT}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_CTL1_OE}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_CTL1_OE}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_CTL2_IN}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_CTL2_IN}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_CTL2_OUT}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_CTL2_OUT}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_CTL2_OE}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_CTL2_OE}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_CTL3_IN}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_CTL3_IN}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_CTL3_OUT}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_CTL3_OUT}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_CTL3_OE}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_CTL3_OE}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_CTL4_IN}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_CTL4_IN}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_CTL4_OUT}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_CTL4_OUT}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_CTL4_OE}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_CTL4_OE}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_CTL5_IN}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_CTL5_IN}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_CTL5_OUT}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_CTL5_OUT}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_CTL5_OE}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_CTL5_OE}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_TECEN_IN}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_TECEN_IN}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_TECEN_OUT}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_TECEN_OUT}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_TECEN_OE}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_TECEN_OE}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_XCLR_IN}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_XCLR_IN}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_XCLR_OUT}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_XCLR_OUT}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_XCLR_OE}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_XCLR_OE}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_XHS_IN}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_XHS_IN}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_XHS_OUT}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_XHS_OUT}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_XHS_OE}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_XHS_OE}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_XMASTER_IN}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_XMASTER_IN}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_XMASTER_OUT}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_XMASTER_OUT}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_XMASTER_OE}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_XMASTER_OE}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_XTRIG_IN}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_XTRIG_IN}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_XTRIG_OUT}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_XTRIG_OUT}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_XTRIG_OE}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_XTRIG_OE}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_XVS_IN}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_XVS_IN}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_XVS_OUT}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_XVS_OUT}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {CMOS_XVS_OE}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {CMOS_XVS_OE}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {I2CSDA_0_IN}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {I2CSDA_0_IN}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {I2CSDA_0_OUT}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {I2CSDA_0_OUT}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {I2CSDA_0_OE}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {I2CSDA_0_OE}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {MUX_GPIO1_IN}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {MUX_GPIO1_IN}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {MUX_GPIO1_OUT}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {MUX_GPIO1_OUT}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {MUX_GPIO1_OE}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {MUX_GPIO1_OE}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {MUX_GPIO2_IN}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {MUX_GPIO2_IN}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {MUX_GPIO2_OUT}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {MUX_GPIO2_OUT}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {MUX_GPIO2_OE}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {MUX_GPIO2_OE}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {MUX_GPIO3_IN}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {MUX_GPIO3_IN}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {MUX_GPIO3_OUT}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {MUX_GPIO3_OUT}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {MUX_GPIO3_OE}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {MUX_GPIO3_OE}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {MUX_GPIO4_IN}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {MUX_GPIO4_IN}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {MUX_GPIO4_OUT}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {MUX_GPIO4_OUT}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {MUX_GPIO4_OE}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {MUX_GPIO4_OE}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {TP_GPIO5_IN}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {TP_GPIO5_IN}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {TP_GPIO5_OUT}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {TP_GPIO5_OUT}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {TP_GPIO5_OE}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {TP_GPIO5_OE}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {TP_GPIO6_IN}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {TP_GPIO6_IN}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {TP_GPIO6_OUT}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {TP_GPIO6_OUT}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {TP_GPIO6_OE}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {TP_GPIO6_OE}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {TP_GPIO7_IN}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {TP_GPIO7_IN}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {TP_GPIO7_OUT}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {TP_GPIO7_OUT}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {TP_GPIO7_OE}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {TP_GPIO7_OE}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {TP_GPIO8_IN}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {TP_GPIO8_IN}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {TP_GPIO8_OUT}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {TP_GPIO8_OUT}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {TP_GPIO8_OE}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {TP_GPIO8_OE}]

# LVDS Rx Constraints
####################

# LVDS TX GPIO Constraints
############################
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_ctl1}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_ctl1}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_ctl4}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_ctl4}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_ctl5}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_ctl5}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_ctl6}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_ctl6}]
# set_input_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_ctl7}]
# set_input_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_ctl7}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_ctl11}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_ctl11}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_ctl12}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_ctl12}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[0]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[0]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[1]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[1]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[2]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[2]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[3]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[3]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[4]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[4]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[5]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[5]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[6]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[6]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[7]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[7]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[8]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[8]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[9]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[9]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[10]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[10]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[11]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[11]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[12]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[12]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[13]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[13]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[14]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[14]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[15]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[15]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[16]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[16]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[17]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[17]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[18]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[18]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[19]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[19]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[20]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[20]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[21]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[21]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[22]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[22]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[23]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[23]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[24]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[24]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[25]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[25]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[26]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[26]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[27]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[27]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[28]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[28]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[29]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[29]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[30]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[30]}]
# set_output_delay -clock <CLOCK> -max <MAX CALCULATION> [get_ports {fx3_data[31]}]
# set_output_delay -clock <CLOCK> -min <MIN CALCULATION> [get_ports {fx3_data[31]}]

# LVDS Tx Constraints
####################

# MIPI RX Constraints
#####################################
set_output_delay -clock syspll_CLKOUT100 -max -3.746 [get_ports {mipi_rx_inst1_VC_ENA[3] mipi_rx_inst1_VC_ENA[2] mipi_rx_inst1_VC_ENA[1] mipi_rx_inst1_VC_ENA[0]}]
set_output_delay -clock syspll_CLKOUT100 -min -2.087 [get_ports {mipi_rx_inst1_VC_ENA[3] mipi_rx_inst1_VC_ENA[2] mipi_rx_inst1_VC_ENA[1] mipi_rx_inst1_VC_ENA[0]}]
set_output_delay -clock syspll_CLKOUT100 -max -4.197 [get_ports {mipi_rx_inst1_CLEAR}]
set_output_delay -clock syspll_CLKOUT100 -min -1.998 [get_ports {mipi_rx_inst1_CLEAR}]
set_input_delay -clock syspll_CLKOUT100 -max 5.394 [get_ports {mipi_rx_inst1_VSYNC[3] mipi_rx_inst1_VSYNC[2] mipi_rx_inst1_VSYNC[1] mipi_rx_inst1_VSYNC[0]}]
set_input_delay -clock syspll_CLKOUT100 -min 2.697 [get_ports {mipi_rx_inst1_VSYNC[3] mipi_rx_inst1_VSYNC[2] mipi_rx_inst1_VSYNC[1] mipi_rx_inst1_VSYNC[0]}]
set_input_delay -clock syspll_CLKOUT100 -max 5.388 [get_ports {mipi_rx_inst1_HSYNC[3] mipi_rx_inst1_HSYNC[2] mipi_rx_inst1_HSYNC[1] mipi_rx_inst1_HSYNC[0]}]
set_input_delay -clock syspll_CLKOUT100 -min 2.694 [get_ports {mipi_rx_inst1_HSYNC[3] mipi_rx_inst1_HSYNC[2] mipi_rx_inst1_HSYNC[1] mipi_rx_inst1_HSYNC[0]}]
set_input_delay -clock syspll_CLKOUT100 -max 5.242 [get_ports {mipi_rx_inst1_VALID}]
set_input_delay -clock syspll_CLKOUT100 -min 2.621 [get_ports {mipi_rx_inst1_VALID}]
set_input_delay -clock syspll_CLKOUT100 -max 5.312 [get_ports {mipi_rx_inst1_CNT[3] mipi_rx_inst1_CNT[2] mipi_rx_inst1_CNT[1] mipi_rx_inst1_CNT[0]}]
set_input_delay -clock syspll_CLKOUT100 -min 2.656 [get_ports {mipi_rx_inst1_CNT[3] mipi_rx_inst1_CNT[2] mipi_rx_inst1_CNT[1] mipi_rx_inst1_CNT[0]}]
set_input_delay -clock syspll_CLKOUT100 -max 5.340 [get_ports {mipi_rx_inst1_DATA[*]}]
set_input_delay -clock syspll_CLKOUT100 -min 2.670 [get_ports {mipi_rx_inst1_DATA[*]}]
set_input_delay -clock syspll_CLKOUT100 -max 5.257 [get_ports {mipi_rx_inst1_ERROR[*]}]
set_input_delay -clock syspll_CLKOUT100 -min 2.628 [get_ports {mipi_rx_inst1_ERROR[*]}]
set_input_delay -clock syspll_CLKOUT100 -max 5.255 [get_ports {mipi_rx_inst1_ULPS_CLK}]
set_input_delay -clock syspll_CLKOUT100 -min 2.627 [get_ports {mipi_rx_inst1_ULPS_CLK}]
set_input_delay -clock syspll_CLKOUT100 -max 5.264 [get_ports {mipi_rx_inst1_ULPS[3] mipi_rx_inst1_ULPS[2] mipi_rx_inst1_ULPS[1] mipi_rx_inst1_ULPS[0]}]
set_input_delay -clock syspll_CLKOUT100 -min 2.632 [get_ports {mipi_rx_inst1_ULPS[3] mipi_rx_inst1_ULPS[2] mipi_rx_inst1_ULPS[1] mipi_rx_inst1_ULPS[0]}]

# Configuration Control Constraints
#####################################
set_output_delay -clock syspll_CLKOUT25 -max -3.360 [get_ports {cfg_CBSEL[0]}]
set_output_delay -clock syspll_CLKOUT25 -max -3.360 [get_ports {cfg_CBSEL[1]}]
set_output_delay -clock syspll_CLKOUT25 -min -2.155 [get_ports {cfg_CBSEL[0]}]
set_output_delay -clock syspll_CLKOUT25 -min -2.155 [get_ports {cfg_CBSEL[1]}]
set_output_delay -clock syspll_CLKOUT25 -max -3.410 [get_ports {cfg_ENA}]
set_output_delay -clock syspll_CLKOUT25 -min -2.155 [get_ports {cfg_ENA}]

# DDR Constraints
#####################
set_output_delay -clock syspll_CLKOUT100 -max -1.810 [get_ports {DDR_CTRL_AADDR_0[*]}]
set_output_delay -clock syspll_CLKOUT100 -min -1.655 [get_ports {DDR_CTRL_AADDR_0[*]}]
set_output_delay -clock syspll_CLKOUT100 -max -1.810 [get_ports {DDR_CTRL_ABURST_0[1] DDR_CTRL_ABURST_0[0]}]
set_output_delay -clock syspll_CLKOUT100 -min -1.655 [get_ports {DDR_CTRL_ABURST_0[1] DDR_CTRL_ABURST_0[0]}]
set_output_delay -clock syspll_CLKOUT100 -max -1.810 [get_ports {DDR_CTRL_AID_0[*]}]
set_output_delay -clock syspll_CLKOUT100 -min -1.655 [get_ports {DDR_CTRL_AID_0[*]}]
set_output_delay -clock syspll_CLKOUT100 -max -1.810 [get_ports {DDR_CTRL_ALEN_0[*]}]
set_output_delay -clock syspll_CLKOUT100 -min -1.655 [get_ports {DDR_CTRL_ALEN_0[*]}]
set_output_delay -clock syspll_CLKOUT100 -max -1.810 [get_ports {DDR_CTRL_ALOCK_0[1] DDR_CTRL_ALOCK_0[0]}]
set_output_delay -clock syspll_CLKOUT100 -min -1.655 [get_ports {DDR_CTRL_ALOCK_0[1] DDR_CTRL_ALOCK_0[0]}]
set_output_delay -clock syspll_CLKOUT100 -max -1.810 [get_ports {DDR_CTRL_ASIZE_0[2] DDR_CTRL_ASIZE_0[1] DDR_CTRL_ASIZE_0[0]}]
set_output_delay -clock syspll_CLKOUT100 -min -1.655 [get_ports {DDR_CTRL_ASIZE_0[2] DDR_CTRL_ASIZE_0[1] DDR_CTRL_ASIZE_0[0]}]
set_output_delay -clock syspll_CLKOUT100 -max -1.810 [get_ports {DDR_CTRL_ATYPE_0}]
set_output_delay -clock syspll_CLKOUT100 -min -1.655 [get_ports {DDR_CTRL_ATYPE_0}]
set_output_delay -clock syspll_CLKOUT100 -max -1.810 [get_ports {DDR_CTRL_AVALID_0}]
set_output_delay -clock syspll_CLKOUT100 -min -1.655 [get_ports {DDR_CTRL_AVALID_0}]
set_output_delay -clock syspll_CLKOUT100 -max -1.810 [get_ports {DDR_CTRL_BREADY_0}]
set_output_delay -clock syspll_CLKOUT100 -min -1.655 [get_ports {DDR_CTRL_BREADY_0}]
set_output_delay -clock syspll_CLKOUT100 -max -1.810 [get_ports {DDR_CTRL_RREADY_0}]
set_output_delay -clock syspll_CLKOUT100 -min -1.655 [get_ports {DDR_CTRL_RREADY_0}]
set_output_delay -clock syspll_CLKOUT100 -max -1.810 [get_ports {DDR_CTRL_WDATA_0[*]}]
set_output_delay -clock syspll_CLKOUT100 -min -1.655 [get_ports {DDR_CTRL_WDATA_0[*]}]
set_output_delay -clock syspll_CLKOUT100 -max -1.810 [get_ports {DDR_CTRL_WID_0[*]}]
set_output_delay -clock syspll_CLKOUT100 -min -1.655 [get_ports {DDR_CTRL_WID_0[*]}]
set_output_delay -clock syspll_CLKOUT100 -max -1.810 [get_ports {DDR_CTRL_WLAST_0}]
set_output_delay -clock syspll_CLKOUT100 -min -1.655 [get_ports {DDR_CTRL_WLAST_0}]
set_output_delay -clock syspll_CLKOUT100 -max -1.810 [get_ports {DDR_CTRL_WSTRB_0[*]}]
set_output_delay -clock syspll_CLKOUT100 -min -1.655 [get_ports {DDR_CTRL_WSTRB_0[*]}]
set_output_delay -clock syspll_CLKOUT100 -max -1.810 [get_ports {DDR_CTRL_WVALID_0}]
set_output_delay -clock syspll_CLKOUT100 -min -1.655 [get_ports {DDR_CTRL_WVALID_0}]
set_input_delay -clock syspll_CLKOUT100 -max 7.310 [get_ports {DDR_CTRL_AREADY_0}]
set_input_delay -clock syspll_CLKOUT100 -min 3.655 [get_ports {DDR_CTRL_AREADY_0}]
set_input_delay -clock syspll_CLKOUT100 -max 7.310 [get_ports {DDR_CTRL_BID_0[*]}]
set_input_delay -clock syspll_CLKOUT100 -min 3.655 [get_ports {DDR_CTRL_BID_0[*]}]
set_input_delay -clock syspll_CLKOUT100 -max 7.310 [get_ports {DDR_CTRL_BVALID_0}]
set_input_delay -clock syspll_CLKOUT100 -min 3.655 [get_ports {DDR_CTRL_BVALID_0}]
set_input_delay -clock syspll_CLKOUT100 -max 7.310 [get_ports {DDR_CTRL_RDATA_0[*]}]
set_input_delay -clock syspll_CLKOUT100 -min 3.655 [get_ports {DDR_CTRL_RDATA_0[*]}]
set_input_delay -clock syspll_CLKOUT100 -max 7.310 [get_ports {DDR_CTRL_RID_0[*]}]
set_input_delay -clock syspll_CLKOUT100 -min 3.655 [get_ports {DDR_CTRL_RID_0[*]}]
set_input_delay -clock syspll_CLKOUT100 -max 7.310 [get_ports {DDR_CTRL_RLAST_0}]
set_input_delay -clock syspll_CLKOUT100 -min 3.655 [get_ports {DDR_CTRL_RLAST_0}]
set_input_delay -clock syspll_CLKOUT100 -max 7.310 [get_ports {DDR_CTRL_RRESP_0[1] DDR_CTRL_RRESP_0[0]}]
set_input_delay -clock syspll_CLKOUT100 -min 3.655 [get_ports {DDR_CTRL_RRESP_0[1] DDR_CTRL_RRESP_0[0]}]
set_input_delay -clock syspll_CLKOUT100 -max 7.310 [get_ports {DDR_CTRL_RVALID_0}]
set_input_delay -clock syspll_CLKOUT100 -min 3.655 [get_ports {DDR_CTRL_RVALID_0}]
set_input_delay -clock syspll_CLKOUT100 -max 7.310 [get_ports {DDR_CTRL_WREADY_0}]
set_input_delay -clock syspll_CLKOUT100 -min 3.655 [get_ports {DDR_CTRL_WREADY_0}]
